on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bunx prettier --check README.md
      - run: bunx biome check --indent-style=space --line-width=100
      - run: bunx tsc **.js --allowJs --checkJs --module preserve --lib esnext,webworker --target esnext --noEmit

